services:
  postgres:
    container_name: PostgresSQL
    image: postgres:alpine
    restart: always
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=picpay-backend-challenge-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  postgres: