server:
  port: 8080

spring:
  application:
    name: @project.artifactId@

  datasource:
    url: jdbc:postgresql://localhost:5432/picpay-backend-challenge-db
    platform: postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format-sql: true

  integration:
    authorize:
      base-url: https://util.devi.tools/api/v2
    notify:
      base-url: https://util.devi.tools/api/v2